version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jdsf-data/app
    container_name: jdsf-data-app
    env_file: .env
    network_mode: host
    tty: true
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    command: ["bash"]
  db:
    image: mysql:latest
    container_name: jdsf-data-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./volumes/var/lib/mysql:/var/lib/mysql
      - ./volumes/etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: jdsf
      MYSQL_PASSWORD: jdsf
      TZ: 'Asia/Tokyo'
    healthcheck:
      test: ["CMD", "mysql", "-ujdsf", "-pjdsf", "-e", "SELECT 1"]
      interval: 6s
      timeout: 1s
      retries: 5
  selenium:
    image: selenium/standalone-chrome:4.19.0-20240328
    container_name: jdsf-data-selenium
    shm_size: 2gb
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - /dev/shm:/dev/shm
    environment:
      SE_START_XVFB: "true"
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
      SE_NODE_MAX_SESSIONS: 1
      JAVA_OPTS: -XX:ActiveProcessorCount=1
      SE_START_VNC: "true"
      SE_START_NO_VNC: "true"
